### PR TITLE
feat(radio): Radio inputs as styled components

### PR DESCRIPTION
**Pull request by elwirra**

### CODE REVIEW

**Comment by macbem** [comment]
@elwirra The intendation is a bit off in most of the files - maybe you forgot to use spaces and Github doesn't handle tabs too well?

**Comment by sztyborek** [comment]
I agree with @macbem, and also, it is possible to change the indentation to 2 spaces for consistency? :)

**Comment by CezaryDanielNowak** [comment]
Guys and gals. My proposition is: use `.editorconfig` for common formating, and eslint (`.eslintrc`) for common linting :-)

**Comment by sztyborek** [comment]
LGTM!

**Pull request merged**
